#!/usr/bin/env bash
# One-click install: Proxy Auth Honeypot on Linux (systemd).
# Usage (from repo root, as root or with sudo):
#   sudo bash deploy/install.sh
# Optional env:
#   INSTALL_DIR=/opt/proxy-honeypot
#   DATA_DIR=/var/lib/proxy-honeypot
#   WEB_BIND=0.0.0.0:8787          # default; set 127.0.0.1:8787 for tunnel-only
#   WEB_USER=admin
#   SKIP_START=1                   # install only, do not start
#   HONEYPOT_USER=honeypot
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/proxy-honeypot}"
DATA_DIR="${DATA_DIR:-/var/lib/proxy-honeypot}"
WEB_BIND="${WEB_BIND:-0.0.0.0:8787}"
WEB_USER="${WEB_USER:-admin}"
HONEYPOT_USER="${HONEYPOT_USER:-honeypot}"
SKIP_START="${SKIP_START:-0}"

RED=$'\033[31m'; GRN=$'\033[32m'; YLW=$'\033[33m'; NC=$'\033[0m'
info() { echo "${GRN}[+]${NC} $*"; }
warn() { echo "${YLW}[!]${NC} $*"; }
die()  { echo "${RED}[x]${NC} $*" >&2; exit 1; }

if [[ "$(id -u)" -ne 0 ]]; then
  die "请用 root 运行: sudo bash deploy/install.sh"
fi

# Locate repo root (script lives in deploy/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
if [[ ! -f "${REPO_ROOT}/pyproject.toml" ]] || [[ ! -d "${REPO_ROOT}/src/honeypot" ]]; then
  die "未找到项目根目录（需要 pyproject.toml 与 src/honeypot）。请在克隆后的仓库内执行。"
fi

info "项目目录: ${REPO_ROOT}"
info "安装到:   ${INSTALL_DIR}"
info "数据目录: ${DATA_DIR}"

# OS packages
if command -v apt-get >/dev/null 2>&1; then
  info "安装系统依赖 (apt)..."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq python3 python3-venv python3-pip ca-certificates curl sqlite3 >/dev/null
elif command -v dnf >/dev/null 2>&1; then
  info "安装系统依赖 (dnf)..."
  dnf install -y python3 python3-pip sqlite >/dev/null
elif command -v yum >/dev/null 2>&1; then
  info "安装系统依赖 (yum)..."
  yum install -y python3 python3-pip sqlite >/dev/null
else
  warn "未识别包管理器，假定 python3/venv 已可用"
fi

command -v python3 >/dev/null || die "需要 python3"
python3 -c 'import sys; exit(0 if sys.version_info >= (3,11) else 1)' \
  || warn "建议 Python ≥ 3.11（当前: $(python3 -V 2>&1)），3.10 可能可用但未保证"

# System user
if ! id -u "${HONEYPOT_USER}" >/dev/null 2>&1; then
  info "创建用户 ${HONEYPOT_USER}"
  useradd -r -m -d "${INSTALL_DIR}" -s /usr/sbin/nologin "${HONEYPOT_USER}" 2>/dev/null \
    || useradd -r -m -d "${INSTALL_DIR}" -s /bin/false "${HONEYPOT_USER}"
fi

mkdir -p "${INSTALL_DIR}" "${DATA_DIR}" "${DATA_DIR}/raw" "${DATA_DIR}/exports" "${DATA_DIR}/backups"

# Sync code (exclude venv/data/.git heavy noise)
info "同步代码到 ${INSTALL_DIR} ..."
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete \
    --exclude '.venv/' --exclude 'venv/' --exclude 'data/' \
    --exclude '.git/' --exclude '__pycache__/' --exclude '*.pyc' \
    --exclude '.pytest_cache/' --exclude 'src/proxy_honeypot.egg-info/' \
    "${REPO_ROOT}/" "${INSTALL_DIR}/"
else
  # fallback: tar pipe
  tar -C "${REPO_ROOT}" \
    --exclude='.venv' --exclude='venv' --exclude='data' --exclude='.git' \
    --exclude='__pycache__' --exclude='.pytest_cache' \
    -cf - . | tar -C "${INSTALL_DIR}" -xf -
fi

# Python venv + install
info "创建 venv 并安装包..."
if [[ ! -d "${INSTALL_DIR}/.venv" ]]; then
  sudo -u "${HONEYPOT_USER}" python3 -m venv "${INSTALL_DIR}/.venv"
fi
# shellcheck disable=SC1091
sudo -u "${HONEYPOT_USER}" "${INSTALL_DIR}/.venv/bin/pip" install -U pip wheel -q
sudo -u "${HONEYPOT_USER}" "${INSTALL_DIR}/.venv/bin/pip" install -e "${INSTALL_DIR}" -q

# .env (generate secrets if missing)
ENV_FILE="${INSTALL_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  info "生成 ${ENV_FILE}（随机 Web 密码）"
  WEB_PASSWORD="$(openssl rand -hex 16 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(16))')"
  WEB_SESSION_SECRET="$(openssl rand -hex 24 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(24))')"
  cat > "${ENV_FILE}" <<EOF
# Generated by deploy/install.sh — chmod 600
DATA_DIR=${DATA_DIR}
CONFIG_PATH=${INSTALL_DIR}/config/config.example.yaml
HONEYPOT_BIND=0.0.0.0
AUTH_MODE=always_fail

WEB_ENABLED=true
WEB_BIND=${WEB_BIND}
WEB_AUTH_USER=${WEB_USER}
WEB_PASSWORD=${WEB_PASSWORD}
WEB_SESSION_SECRET=${WEB_SESSION_SECRET}

EVENTS_RETENTION_DAYS=90
JSONL_RETENTION_DAYS=180
LOG_LEVEL=info
EOF
  chmod 600 "${ENV_FILE}"
  CREATED_ENV=1
else
  warn "已存在 ${ENV_FILE}，不覆盖"
  CREATED_ENV=0
  # shellcheck disable=SC1090
  set -a; source "${ENV_FILE}"; set +a
  WEB_PASSWORD="${WEB_PASSWORD:-<见 .env>}"
fi

chown -R "${HONEYPOT_USER}:${HONEYPOT_USER}" "${INSTALL_DIR}" "${DATA_DIR}"
chmod 600 "${ENV_FILE}" || true

# systemd unit
info "安装 systemd 服务..."
UNIT_SRC="${INSTALL_DIR}/deploy/proxy-honeypot.service"
UNIT_DST="/etc/systemd/system/proxy-honeypot.service"
# rewrite paths if custom INSTALL_DIR
sed \
  -e "s|/opt/proxy-honeypot|${INSTALL_DIR}|g" \
  -e "s|User=honeypot|User=${HONEYPOT_USER}|g" \
  -e "s|Group=honeypot|Group=${HONEYPOT_USER}|g" \
  "${UNIT_SRC}" > "${UNIT_DST}"

systemctl daemon-reload
systemctl enable proxy-honeypot.service

if [[ "${SKIP_START}" != "1" ]]; then
  info "启动服务..."
  systemctl restart proxy-honeypot.service
  sleep 1
  systemctl --no-pager --full status proxy-honeypot.service || true
fi

# Summary
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
HOST_IP="${HOST_IP:-YOUR_SERVER_IP}"
WEB_PORT="$(echo "${WEB_BIND}" | awk -F: '{print $NF}')"

echo
echo "=============================================="
echo "  Proxy Auth Honeypot 安装完成"
echo "=============================================="
echo "  安装目录: ${INSTALL_DIR}"
echo "  数据目录: ${DATA_DIR}"
echo "  服务名:   proxy-honeypot"
echo "  Web:      http://${HOST_IP}:${WEB_PORT}"
echo "  用户:     ${WEB_USER}"
if [[ "${CREATED_ENV}" == "1" ]]; then
  echo "  密码:     ${WEB_PASSWORD}"
  echo "  (已写入 ${ENV_FILE}，请立即保存并考虑改密)"
else
  echo "  密码:     见 ${ENV_FILE} 中 WEB_PASSWORD"
fi
echo
echo "  健康检查: curl -s http://127.0.0.1:${WEB_PORT}/healthz"
echo "  日志:     journalctl -u proxy-honeypot -f"
echo "  备份:     sudo -u ${HONEYPOT_USER} bash ${INSTALL_DIR}/scripts/backup.sh"
echo
echo "  云安全组: 蜜罐代理端口 → 0.0.0.0/0；Web/SSH → 仅管理 IP"
echo "  AI 配置:  登录 Web → AI 页面（不写 .env）"
echo "  永不转发: 本服务不是开放代理"
echo "=============================================="
